name: layrz_ble_example
description: "Demonstrates how to use the layrz_ble plugin."
publish_to: 'none'

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  permission_handler: ^11.3.1
  layrz_icons: any
  layrz_theme: any
  layrz_models: any
  layrz_ble:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
