name: layrz_ble
description: "A simple way to interact with BLE devices in Flutter."
version: 1.0.0
homepage: https://github.com/goldenm-software/layrz_ble
publish_to: "pub.dev"

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: '>=3.27.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  web: ^1.1.0
  plugin_platform_interface: ^2.0.2
  collection: ^1.18.0
  layrz_models: ^3.3.21
  flutter_web_bluetooth: ^1.0.0
  bluez: ^0.8.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.layrz.layrz_ble
        pluginClass: LayrzBlePlugin
      ios:
        pluginClass: LayrzBlePlugin
      macos:
        pluginClass: LayrzBlePlugin
      windows:
        pluginClass: LayrzBlePluginCApi
      web:
        pluginClass: LayrzBlePluginWeb
        fileName: platforms/web.dart
      linux:
        dartPluginClass: LayrzBlePluginLinux
        fileName: platforms/linux.dart